CREATE TABLE IF NOT EXISTS media_assets (
  id VARCHAR(64) PRIMARY KEY,
  article_id VARCHAR(128) NOT NULL,
  chapter_id VARCHAR(128) NULL,
  paragraph_index INT NULL,
  range_start_paragraph_index INT NULL,
  range_start_offset INT NULL,
  range_end_paragraph_index INT NULL,
  range_end_offset INT NULL,
  media_type ENUM('image', 'audio') NOT NULL,
  url VARCHAR(2048) NOT NULL,
  source_url VARCHAR(2048) NULL,
  file_path VARCHAR(1024) NULL,
  prompt MEDIUMTEXT NULL,
  source_text MEDIUMTEXT NULL,
  provider VARCHAR(64) NOT NULL DEFAULT 'minimax',
  model VARCHAR(128) NULL,
  user_id VARCHAR(128) NOT NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_media_assets_position (
    article_id,
    chapter_id,
    paragraph_index,
    range_start_paragraph_index,
    range_start_offset
  ),
  INDEX idx_media_assets_user (user_id, created_at),
  INDEX idx_media_assets_type (media_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
